l_english:
 SETTING_VALUE_WARNING: "$VALUE|0X$"
 SETTING_VALUE_PERCENTAGE_WARNING: "$VALUE|%0X$"
 RECOMMENDED_GUI_SCALE_TOO_HIGH: "#X Una scalabilità superiore a $VALUE|%0$ causerà la comparsa delle interfacce fuori dallo schermo!#"
 RECOMMENDED_GUI_SCALE: "Una scalabilità superiore a $VALUE|%0$ causerà la comparsa delle interfacce fuori dallo schermo"
