l_english:
 # General 
 SETTING_VALUE_NONE: "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
 SETTING_VALUE_SECONDS: "$VALUE$ secondi"
 SETTING_VALUE_MINUTES: "$VALUE$ minuti"

 # Graphics
 SETTING_RENDERER: "Renderer"
 SETTING_RENDERER_TOOLTIP: "Determina quale renderer viene utilizzato."
 SETTING_VSYNC: "VSync"
 SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Sincronizza il frame rate del gioco con quello del monitor, riducendo l'effetto di screen tearing.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_PORTRAIT_MULTI_SAMPLING: "Multicampionamento ritratti"
 SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Utilizza il multicampionamento per l'Alpha-To-Coverage per rendere più fluido l'effetto dei capelli.\n\nImpostazioni più basse aumentano le prestazioni."
 SETTING_MULTI_SAMPLING: "Anti-aliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!L'uso del multicampionamento anti-aliasing (MSAA) rende i bordi delle immagini più smussati.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_ANTI_ALIASING: "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!L'uso dell'anti-aliasing rende i bordi delle immagini più smussati.\n\nSi raccomanda l'uso di FXAA."
 OPTION_ANTI_ALIASING_DISABLED: "Disattivato"
 OPTION_ANTI_ALIASING_FXAA: "FXAA"
 SETTING_UPSCALE: "Metodo di Upscale"
 SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nI metodi di upscale permettono di ottenere una risoluzione del display più elevata tramite un campionamento algoritmico. Questo può migliorare le prestazioni, ma potrebbe causare artefatti visivi o comportamenti imprevisti.\n\nI metodi disponibili dipendono dalla scheda grafica in uso."
 OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
 OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
 OPTION_UPSCALE_XESS: "Intel® XeSS"
 SETTING_UPSCALE_QUALITY: "Qualità Upscale"
 SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nImposta il focus del metodo di upscaling, passando dalla massima qualità alle massime prestazioni."
 OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Qualità Ultra"
 OPTION_UPSCALE_QUALITY_QUALITY: "Qualità"
 OPTION_UPSCALE_QUALITY_BALANCED: "Equilibrato"
 OPTION_UPSCALE_QUALITY_PERFORMANCE: "Prestazioni"
 OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Prestazioni Ultra"
 SETTING_ANISOTROPIC_FILTERING: "Filtraggio texture"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!L'uso del filtraggio anisotropico migliora l'aspetto delle superfici texturizzate.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_RESOLUTION: "Risoluzione"
 SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Imposta la qualità dell'immagine del gioco.\n\nRisoluzioni più basse possono aumentare le prestazioni.\n\n#X Una risoluzione con un rapporto d'aspetto non supportato potrebbe causare la comparsa dell'interfaccia fuori dallo schermo#!"
 SETTING_RENDER_SCALE: "Scala di rendering"
 SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nLa scala della risoluzione di rendering del gioco relativa alla risoluzione principale, esclusa l'interfaccia utente.\n\nImpostazioni più basse possono aumentare le prestazioni a scapito della fedeltà visiva; superare il 100% migliora la fedeltà ma ridurrà probabilmente le prestazioni."
 SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
 SETTING_DISPLAY: "Monitor"
 SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Se il computer dispone di più monitor, scegli quello da utilizzare per il gioco."
 SETTING_GRAPHICS_DEVICE: "Scheda grafica"
 SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Seleziona quale scheda grafica verrà utilizzata dal gioco.\n\nL'uso di una scheda grafica integrata o di un renderer software può diminuire le prestazioni."
 SETTING_SHADOW_MAP_RESOLUTION: "Qualità ombre"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Determina la risoluzione con cui vengono renderizzate le mappe delle ombre, se attivate.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_DISPLAY_MODE: "Modalità schermo"
 SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Determina come visualizzare il gioco sullo schermo."
 SETTING_BLOOM_QUALITY: "Bloom"
 SETTING_MESH_LOD_BIAS: "Qualità Mesh LOD"
 SETTING_MESH_LOD_FADE: "Dissolvenza Mesh LOD"
 SETTING_TERRAIN_SMOOTHING: "Levigatura terreno"
 OPTION_FULLSCREEN: "Schermo intero"
 OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Visualizza il gioco utilizzando l'intero schermo. La risoluzione impostata determinerà la nitidezza dell'immagine."
 OPTION_WINDOWED: "Finestra"
 OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Visualizza il gioco in una finestra. La risoluzione impostata determina la dimensione della finestra."
 OPTION_DISABLED: "Disattivato"
 OPTION_OFF: "No"
 OPTION_LOW: "Bassa"
 OPTION_MEDIUM: "Media"
 OPTION_HIGH: "Alta"
 OPTION_VERY_HIGH: "Molto alta"
 OPTION_ULTRA: "Ultra"
 OPTION_CUSTOM: "Personalizzata"
 OPTION_DEFAULT: "Predefinita"
 SETTINGS_CATEGORY_UI: "Interfaccia"
 SETTINGS_CATEGORY_GAME: "Gioco"
 SETTING_TEXTURE_QUALITY: "Qualità texture"
 SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nControlla la risoluzione delle texture caricate.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_QUALITY: "Preset qualità"
 SETTING_SFX: "Effetti sonori"
 SETTING_UI: "Interfaccia"
 SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Seleziona un preset per le opzioni grafiche avanzate sottostanti.\n\nUn preset basso aumenterà le prestazioni."
 SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Attiva l'effetto 'bloom', dove le luci estremamente intense sbordano su altre parti dell'immagine.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Attiva la profondità di campo per simulare l'obiettivo di una macchina fotografica, sfocando i punti dell'immagine non a fuoco.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Attiva l'effetto riflesso lente (lens flare) nelle aree con alto bloom. Il bloom deve essere attivo affinché l'effetto sia visibile.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Attiva un effetto riflesso lente secondario nelle aree con alto bloom. Il bloom deve essere attivo affinché l'effetto sia visibile.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Determina se applicare alla mappa l'occlusione ambientale nello spazio dello schermo (SSAO).\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_REFRACTION_TOOLTIP: "Determina se le rifrazioni appaiono o meno sull'acqua."
 SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nControlla la qualità delle rifrazioni dell'acqua, se attivate.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nDetermina il livello massimo di qualità degli oggetti sulla mappa (come gli edifici).\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nDetermina la qualità dei LOD (livelli di dettaglio) sugli oggetti della mappa, come i modelli delle unità.\n\nImpostazioni più basse possono aumentare le prestazioni."
 SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Se attivo, i modelli 3D passano fluidamente tra i diversi livelli di dettaglio (LOD) quando si aumenta o diminuisce lo zoom.\n\nDisattivarlo può aumentare le prestazioni."
 SETTING_PROVINCE_NAMES_TOOLTIP: "Determina come i nomi delle città e delle province appaiono sulla mappa."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Determina se il terreno impercorribile è incluso all'interno dei confini di una nazione sulla mappa."
 SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nDetermina la lingua dell'interfaccia utente."
 SETTING_ACCOUNT_EMAIL_TOOLTIP: "L'e-mail del suo account Paradox"
 SETTING_FRAMERATE_CAP: "FPS massimi"
 SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nIl numero massimo di FPS (fotogrammi al secondo) che il gioco renderizzerà.\n\nImpostazioni più basse possono ridurre il consumo energetico."
 OPTION_CAP_30: "30"
 OPTION_CAP_60: "60"
 OPTION_CAP_90: "90"
 OPTION_CAP_120: "120"
 OPTION_CAP_144: "144"
 OPTION_CAP_165: "165"
 SETTING_TEXTURE_STREAMING: "Streaming texture"
 SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nLe texture vengono caricate solo quando necessario.\n\nRiduce l'utilizzo della memoria GPU al costo di un certo carico sulla CPU. Può migliorare le prestazioni per le GPU con poca memoria."
 SETTING_TEXTURE_STREAMING_CACHE: "Dimensione cache streaming texture"
 SETTING_VALUE_MB: "$VALUE$ MB"

 # GUI
 SETTING_ANIMATION_SPEED: "Velocità animazioni"
 SETTING_GUI_SCALING: "Scalabilità interfaccia (GUI)"
 SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Imposta la scala dell'intera interfaccia utente. Utile per risoluzioni dello schermo elevate.\n\n#X Un valore troppo alto farà sì che le interfacce non rientrino correttamente nello schermo!#!"
 SETTING_TOOLS_GUI_SCALING: "Scalabilità interfaccia strumenti"
 SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Imposta la scala dell'interfaccia degli strumenti. Utile per risoluzioni dello schermo elevate.\n\n#X Un valore troppo alto farà sì che le interfacce non rientrino correttamente nello schermo!#!"

 # System
 SETTING_SCREEN_EDGE_SCROLL_MODE: "Scorrimento mouse"
 SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Libero"
 SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 direzioni"
 SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Disattivato"
 SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nDetermina come si comporta la telecamera quando si scorre con il mouse."
 SETTING_SCROLL_SPEED: "Velocità scorrimento"
 SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nImposta la velocità di scorrimento della mappa quando si usa la tastiera o il mouse."
 SETTING_CAMERA_ROTATION_SPEED: "Velocità rotazione telecamera"
 SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nLa velocità di rotazione della telecamera."
 SETTING_ZOOM_SPEED: "Velocità zoom"
 SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nLa velocità di zoom della telecamera."
 SETTING_MOUSE_CURSOR_ZOOM_MODE: "Comportamento zoom"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Relativo al cursore"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Zoom sul cursore"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ignora cursore"
 SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nDetermina come si comporta la telecamera rispetto al cursore del mouse durante lo zoom."
 SETTING_INPUT_DEVICE: "Dispositivo di input"
 SETTING_EDITOR: "Editor"
 SETTING_EDITOR_POSTFIX: "Postfix editor"
 SETTING_EDITOR_OPEN_FILE_FORMAT: "Comando apertura editor"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Comando visualizzazione log"
 SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Comando apertura editor di codice"
 SETTING_GRACEFUL_EXIT: "Chiusura controllata"
 SETTING_LANGUAGE: "Lingua"
 MOUSE_AND_KEYBOARD: "Mouse e tastiera"
 GAMEPAD: "Gamepad"
 SETTING_MULTISAMPLING_DISABLED: "Disattivato"
 SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Disattivato"
 SETTING_ANISOTROPIC_FILTERING_DISABLED: "Disattivato"

 # Editor
 SETTING_CAMERA_TILT: "Inclinazione telecamera"
 SETTING_CAMERA_STRATEGY: "Tipo telecamera"
 SETTING_CENTERED_ZOOM_IN: "Zoom centrato"
 SETTING_CAMERA_SPEED: "Velocità telecamera"
 CAMERA_TABLETOP: "Dall'alto"
 CAMERA_FPS: "Prima persona"
 CAMERA_WASD: "Stile WASD"

 # Audio
 SETTING_Music: "Musica"
 SETTING_Ambient: "Ambiente"
 SETTING_Effects: "Effetti"
 SETTING_Master: "Master"
 SETTING_VO: "Doppiaggio"
 SETTING_VO_TOOLTIP: "#T Volume doppiaggio\n#!Imposta il volume dei dialoghi e delle voci nel gioco."
 SETTING_Master_TOOLTIP: "#T Volume Master\n#!Imposta il volume generale di tutti i suoni del gioco."
 SETTING_Music_TOOLTIP: "#T Volume musica\n#!Imposta il volume della musica."
 SETTING_Ambient_TOOLTIP: "#T Volume ambiente\n#!Imposta il volume dei suoni ambientali."
 SETTING_SFX_TOOLTIP: "#T Volume SFX\n#!Imposta il volume degli effetti sonori, come i combattimenti."
 SETTING_UI_TOOLTIP: "#T Volume interfaccia\n#!Imposta il volume dell'interfaccia utente."
 SETTING_AUDIO_DEBUG_LOG_LEVEL: "Livello log di debug"
 SETTING_AUDIO_DEVICE_PROFILE: "Profilo audio"
 SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Scelga il profilo audio più adatto a sua configurazione."
 SETTING_AUDIO_OPTION_SPEAKERS: "Altoparlanti"
 SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Missaggio predefinito per $SETTING_AUDIO_OPTION_SPEAKERS$."
 SETTING_AUDIO_OPTION_HEADPHONES: "Cuffie"
 SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Missaggio regolato per $SETTING_AUDIO_OPTION_HEADPHONES$."
 SETTING_AUDIO_OPTION_TV: "TV"
 SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Missaggio per $SETTING_AUDIO_OPTION_TV$ e altoparlanti del monitor."
 SETTING_AUDIO_OPTION_NIGHTMODE: "Modalità notte"
 SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Attenua il suono per le sessioni notturne, riducendo i toni acuti e comprimendo la gamma dinamica."
 SETTING_MUSIC_DENSITY: "Densità musicale"
 SETTING_MUSIC_DENSITY_TOOLTIP: "Controlla l'equilibrio tra brani completi, silenzio e segmenti musicali d'atmosfera.\n\nIntensa = Principalmente brani riprodotti uno dopo l'altro.\nBilanciata = Equilibrio tra brani, silenzio e atmosfera.\nRilassata = Principalmente segmenti rilassanti che offrono un'esperienza d'atmosfera migliore e meno ripetitiva."

 # Game
 SETTING_AUTOSAVE: "Intervallo salvataggio automatico"
 SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Imposta la frequenza con cui il gioco salva automaticamente."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Determina se i salvataggi automatici vengono salvati sul cloud o meno."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Determina se la telecamera debba essere sempre rivolta a nord o meno."
 NO_AUTOSAVE: "Nessun salvataggio automatico"
 SETTING_ENABLE_PARTICLES: "Attiva particelle"
 SETTING_ENABLE_PARTICLES_TOOLTIP: "#T $SETTING_ENABLE_PARTICLES$\n#!Attiva o disattiva gli effetti particellari nel gioco."

 # Multiplayer
 SETTINGS_FILE_TRANSFER_SPEED: "Velocità trasferimento file"
 SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$#!\nImposta la velocità massima per il trasferimento dei file di salvataggio nella lobby multigiocatore.\n\nValori più bassi potrebbero migliorare la stabilità della rete, ma aumenteranno i tempi di caricamento.\n\nL'host della partita determina la velocità massima.\n"

 # Tools
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Salvataggio automatico editor mappe (minuti)"
 SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Intervallo di salvataggio automatico dell'editor mappe (minuti)"
 SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Modalità trascinamento editor nodi"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Completamento automatico console"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Espansione completa, itera con tab"
 SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Espansione parziale fino alla differenza"

 # Accessibility
 SETTINGS_CATEGORY_ACCESSIBILITY: "Accessibilità"
 SETTING_COLOR_BLIND_MODE: "Modalità daltonismo"
 SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Cambia i colori utilizzati nei testi del gioco con un set più facile da distinguere per i diversi tipi di daltonismo."